<!--SLIDE INTRO PARALLAX-->
<div class="slide-parallax" id="slide" data-type="background" data-speed="3"></div>
<section class="catalogue-band" id="catalogueBand">
    <h1>Notre Catalogue</h1>
    <h3>Nos Artistes</h3>
    <div class="catalogue-content">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab accusantium at blanditiis dicta dolorem, doloribus enim error eveniet facere libero nam neque nihil odio odit optio perferendis quas quasi qui quia quibusdam quos ratione sequi soluta totam, unde velit veritatis vero. Architecto dolore, est iure laudantium tempora temporibus vero voluptas!</p>
    </div>
<!--    BAND CARD CONTAINER-->
    <div class="band-container-mobile band-container">
        <div class="band-card-container">
            <div class="band-card" id="bandCard">
                <div class="filter" id="filter" onmouseover="cardEffect()">
                    <div class="card-top">

                    </div>
                    <div class="card-center">

                    </div>
                    <div class="card-bottom">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, vitae!</p>
                        <div class="social-logo">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-instagram-square"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-youtube"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="band-card">
                <div class="filter">
                    <div class="card-top">

                    </div>
                    <div class="card-center">

                    </div>
                    <div class="card-bottom">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, vitae!</p>
                        <div class="social-logo">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-instagram-square"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-youtube"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="band-card">
                <div class="filter">
                    <div class="card-top">

                    </div>
                    <div class="card-center">

                    </div>
                    <div class="card-bottom">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, vitae!</p>
                        <div class="social-logo">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-instagram-square"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-youtube"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="band-card">
                <div class="filter">
                    <div class="card-top">

                    </div>
                    <div class="card-center">

                    </div>
                    <div class="card-bottom">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere, vitae!</p>
                        <div class="social-logo">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-instagram-square"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fab fa-youtube"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="news">
    <h1>Hello</h1>
    <h3>What's new here
        <i class="fas fa-question"></i>
    </h3>
    <div class="news-container">
        <div class="news-card">
            <div class="news-top">
                <div class="img"></div>
            </div>
            <div class="news-bottom">
                <h4>TITRE</h4>
                <h5>12/05/2020</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet animi est, numquam quidem voluptas voluptates voluptatum. Distinctio enim iusto perspiciatis sunt voluptatum? Ad aliquam, aliquid blanditiis culpa eaque eligendi harum illo magnam, neque odit pariatur quibusdam voluptatem? Accusantium, aliquam asperiores beatae excepturi inventore libero necessitatibus, nulla quo quod similique vero.</p>
            </div>
        </div>
        <div class="news-card">
            <div class="news-top">
                <div class="img"></div>
            </div>
            <div class="news-bottom">
                <h4>TITRE</h4>
                <h5>12/05/2020</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet animi est, numquam quidem voluptas voluptates voluptatum. Distinctio enim iusto perspiciatis sunt voluptatum? Ad aliquam, aliquid blanditiis culpa eaque eligendi harum illo magnam, neque odit pariatur quibusdam voluptatem? Accusantium, aliquam asperiores beatae excepturi inventore libero necessitatibus, nulla quo quod similique vero.</p>
            </div>
        </div>
        <div class="news-card">
            <div class="news-top">
                <div class="img"></div>
            </div>
            <div class="news-bottom">
                <h4>TITRE</h4>
                <h5>12/05/2020</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet animi est, numquam quidem voluptas voluptates voluptatum. Distinctio enim iusto perspiciatis sunt voluptatum? Ad aliquam, aliquid blanditiis culpa eaque eligendi harum illo magnam, neque odit pariatur quibusdam voluptatem? Accusantium, aliquam asperiores beatae excepturi inventore libero necessitatibus, nulla quo quod similique vero.</p>
            </div>
        </div>
        <div class="news-card">
            <div class="news-top">
                <div class="img"></div>
            </div>
            <div class="news-bottom">
                <h4>TITRE</h4>
                <h5>12/05/2020</h5>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet animi est, numquam quidem voluptas voluptates voluptatum. Distinctio enim iusto perspiciatis sunt voluptatum? Ad aliquam, aliquid blanditiis culpa eaque eligendi harum illo magnam, neque odit pariatur quibusdam voluptatem? Accusantium, aliquam asperiores beatae excepturi inventore libero necessitatibus, nulla quo quod similique vero.</p>
            </div>
        </div>
    </div>

</section>
