<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://kit.fontawesome.com/5138cb0aad.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/css/reset.css">
    <link href="https://fonts.googleapis.com/css2?family=Hind:wght@300&family=Lato&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/main.css">
    <title>Bacon Record</title>
</head>
<body>
    <!--HEADER-->
    <header class="header-mobile">
        <div class="navbar-logo-container">
            <navbar class="navbar-mobile">
                <ul>
                    <li>Home</li>
                </ul>
            </navbar>
            <div class="logo-container-mobile" id="logoContainerMobile" onclick="openHiddenMenuMobile()">
                <i class="fas fa-bars"></i>
            </div>
        </div>
        <div class="hidden-menu-mobile" id="hiddenMenuMobile">
            <ul>
                <li class="hidden-sub-menu-mobile">
                    <a href="#">News</a>
                </li>
                <li class="hidden-sub-menu-mobile">
                    <a href="#">Catalogue</a>
                </li>
                <li class="hidden-sub-menu-mobile">
                    <a href="#">Média</a>
                </li class="hidden-sub-menu-mobile">
            </ul>
        </div>
    </header>
    <header class="header" id="header">
        <navbar class="navbar" id="navbar">
            <ul class="main-menu">
                <li class="main-menu-li">
                    <a href="#">Home</a>
                </li>
                <li class="main-menu-li">
                    <a href="#">News</a>
                </li>
                <li class="main-menu-li">
                    <a href="#">Média</a>
                </li>
                <li class="catalogue-hover">
                    Catalogue
                    <ul class="sub-menu-navbar">
                        <li>
                            <a href="#">I Am John Baudelaire</a>
                        </li>
                        <li>
                            <a href="#">Tomoe</a>
                        </li>
                        <li>
                            <a href="#">Your Day Will Come</a>
                        </li>
                        <li>
                            <a href="#">No One Can Hear You Scream!</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </navbar>
        <div class="logo-container">
            <a href="">
                <i class="fas fa-piggy-bank" id="logo"></i>
            </a>
        </div>
    </header>
    <!--MAIN-->
    <main class="main-content">
        <?php include $template.'.phtml' ?>
    </main>
    <!--FOOTER-->
    <footer class="footer">

    </footer>
    <script src="scripts/navbarEffect.js"></script>
    <script src="scripts/parallaxEffect.js"></script>
</body>
</html>