<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://kit.fontawesome.com/5138cb0aad.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/css/reset.css">
    <link href="https://fonts.googleapis.com/css2?family=Hind:wght@300&family=Lato&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/main.css">
    <title>Bacon Record</title>
</head>
<body>
    <!--HEADER-->
    <header class="header">
        <navbar class="navbar">
            <ul>
                <li>Home</li>
                <li class="sub-menu">News</li>
                <li class="sub-menu">Catalogue</li>
                <li class="sub-menu">News</li>
                <li class="sub-menu">Média</li>
            </ul>
        </navbar>
        <div class="logo-container">
            <a href="#">
                <i class="fas fa-piggy-bank" id="logo"></i>
            </a>
        </div>
    </header>
</body>
</html>