<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://kit.fontawesome.com/5138cb0aad.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="assets/css/reset.css">
    <link href="https://fonts.googleapis.com/css2?family=Hind:wght@300&family=Lato&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/main.css">
    <title>Bacon Record</title>
</head>
<body>
    <!--HEADER-->
    <header class="header-mobile">
        <navbar class="navbar-mobile">
            <ul>
                <li>Home</li>
            </ul>
        </navbar>
        <div class="logo-container-mobile" id="logoContainerMobile" onclick="openHiddenMenuMobile()">
            <a href="#">
                <i class="fas fa-piggy-bank"></i>
            </a>
        </div>
    </header>
    <div class="hidden-menu-mobile" id="hiddenMenuMobile">
        <ul>
            <li class="hidden-sub-menu-mobile">
                <a href="#">News</a>
            </li>
            <li class="hidden-sub-menu-mobile">
                <a href="#">Catalogue</a>
            </li>
            <li class="hidden-sub-menu-mobile">
                <a href="#">Média</a>
            </li class="hidden-sub-menu-mobile">
        </ul>
    </div>
    <header class="header">
        <navbar class="navbar">
            <ul>
                <li>
                    <a href="#">Home</a>
                </li>
                <li>
                    <a href="#">News</a>
                </li>
                <li>
                    <a href="#">Catalogue</a>
                </li>
                <li>
                    <a href="#">Média</a>
                </li>
            </ul>
        </navbar>
        <div class="logo-container">
            <a href="#">
                <i class="fas fa-piggy-bank" id="logo"></i>
            </a>
        </div>
    </header>
    <!--MAIN-->
    <main>

    </main>
    <!--FOOTER-->
    <footer class="footer">
        <div class="social-logo">
            <ul>
                <li>
                    <a href="#">
                        <i class="fab fa-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fab fa-instagram-square"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fab fa-youtube"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
    <script src="scripts/navbarEffect.js"></script>
</body>
</html>